### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by nnthnn** [jaguarnac/atom-quoteswap#1]
I tried the shortcut and the running the command from the command palette. Both executions result in nothing changing.

Atom 1.0.7
OSX 10.10.5

**Comment by jaguarnac** [comment]
@njlg 
Confirmed not working. Will debug and update soon.

**Comment by jaguarnac** [comment]
Turns out, if the package.json declares activationCommand, the package doesn't activate itself.
Removing it seems to have fixed the problem.

Running  Atom Quoteswap : swap command should now properly swap the quotes.
